name: Check server

on: push

jobs:
  lint-server:
    runs-on: self-hosted
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use node
        uses: actions/setup-node@v2
        with:
          node-version: '20.4.0'
      - name: Install deps
        working-directory: ./server
        run: npm ci
        shell: bash
      - name: Lint
        working-directory: ./server
        run: npm run lint